version: 2
plan:
  project-key: DEMO
  key: SIMPLE
  name: Simple Plan
stages:
  - Stage 1:
      jobs:
        - JOB1
jobs:
  JOB1:
    name: "Job 1"
    tasks:
      - checkout:
          description: "Checkout source"
      - script:
          description: "Print Hello"
          scripts:
            - echo "Hello, Bamboo!"
